### ISSUE TITLE
python3 vis_det.py --vname **.mp4 

### ISSUE THREAD

**Issue by cuge1995** [MCG-NJU/MOC-Detector#12]
```shell
Traceback (most recent call last):
  File "vis_det.py", line 174, in <module>
    det()
  File "vis_det.py", line 148, in det
    opt = opts().parse()
  File "/MOC-Detector/src/vis/tiny_opt.py", line 77, in parse
    opt.vname = opt.vname.split('_')[1] + '/' + opt.vname
IndexError: list index out of range
```

**Comment by ArchiZX** [comment]
Please choose videos from https://github.com/MCG-NJU/MOC-Detector/blob/master/src/vis/test_video_list.txt.
