### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by npduyduc** [MCG-NJU/MOC-Detector#9]
I'm now trying to train your model with my custom dataset.
I tried using brox optical flow but it didn't work, so I used dense optical flow instead.
However, when I started training, I got an error like this:
```
Train_K7_flow_cocoTraceback (most recent call last):
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/train.py", line 167, in <module>
    main(opt)
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/train.py", line 95, in main
    log_dict_train = trainer.train(epoch, train_loader, train_writer)
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/trainer/moc_trainer.py", line 56, in train
    return self.run_epoch('train', epoch, data_loader, writer)
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/trainer/moc_trainer.py", line 74, in run_epoch
    for iter, batch in enumerate(data_loader):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/datasets/sample/sampler.py", line 120, in __getitem__
    draw_umich_gaussian(hm[ilabel], center_int, radius)
IndexError: index 20 is out of bounds for axis 0 with size 4
```
When I checked, brox-images are (240, 320, 3) and dense-images are the same, so I don't understand how your algorithms think they are different.
This is the image after I use dense optical flow
![00004](https://user-images.githubusercontent.com/49702102/88511834-bcde6600-d00f-11ea-8942-9c2f9138aa6a.jpg)
This is the image after I use dense optical flow and Raises pixel 0 to 128
![00007](https://user-images.githubusercontent.com/49702102/88511972-fadb8a00-d00f-11ea-80af-5062d449b8b2.jpg)
I tried both and failed at the same error :( 
Can you help me? Thank you!

**Comment by ArchiZX** [comment]
`index 20 is out of bounds for axis 0 with size 4`
I doubt that you define dataset `num_classes` as 4 but use ground truth annotations above this range.
Please check your ground truth annotations which label number should in range `0, 1, 2, 3`.

**Comment by npduyduc** [comment]
Thank you, this bug has been resolved
I was able to run a model train with my custom dataset but when I predicted it had this error:
```
Traceback (most recent call last):
  File "det.py", line 27, in <module>
    normal_inference(opt)
  File "/home/ryan/Desktop/PythonPJ/human-activity-recognition/MOC-Detector/src/inference/normal_inference.py", line 111, in normal_inference
    for iter, data in enumerate(data_loader):
  File "/home/ryan/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/ryan/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/ryan/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ryan/anaconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ryan/Desktop/PythonPJ/human-activity-recognition/MOC-Detector/src/inference/normal_inference.py", line 63, in __getitem__
    images = [cv2.imread(self.imagefile(v, frame + i)).astype(np.float32) for i in range(self.opt.K)]
  File "/home/ryan/Desktop/PythonPJ/human-activity-recognition/MOC-Detector/src/inference/normal_inference.py", line 63, in <listcomp>
    images = [cv2.imread(self.imagefile(v, frame + i)).astype(np.float32) for i in range(self.opt.K)]
AttributeError: 'NoneType' object has no attribute 'astype'
```
This error seems to be that UCF101.imagefile does not load my images (I added 1 class in your ucf24 dataset).
I fixed num_classes, and gttubes look like this image:
![Screenshot from 2020-07-31 10-15-25](https://user-images.githubusercontent.com/49702102/88996298-121fbd80-d317-11ea-8393-c28108436dc5.png)
My new class directory structure is this:

```

> - ucf24
> - - brox-images
> - - - ...
> - - - RaiseTwoHand
> - - - - 001
> - - - - ...
> - - - - 022
> - - rgb-images
> - - - ...
> - - - RaiseTwoHand
> - - - - 001
> - - - - ...
> - - - - 022
> - - - UCF101v2-GT.pkl

```
Can you explan for me what did I miss ?

**Comment by ArchiZX** [comment]
Never mind.

**Comment by ArchiZX** [comment]
Hi~
We upload visualization codes and I hope it can help you.

**Comment by npduyduc** [comment]
Wow that's great! i'm trying your visualization codes, it works really well according to your instructions.
But when I replace your model with my model, I get this error
I changed the label_class in vis_utils.py and --rgb_model
```
loaded /home/ryan/Desktop/PythonPJ/human-activity-recognition/MOC-Detector/experiment/result_model/Train_K7_rgb_coco/model_[12]_2020-08-02-12-02.pth, epoch 12
Traceback (most recent call last):
  File "vis_det.py", line 174, in <module>
    det()
  File "vis_det.py", line 157, in det
    stream_inference(opt)
  File "vis_det.py", line 125, in stream_inference
    detector = MOCDetector(opt)
  File "../detector/stream_moc_det.py", line 29, in __init__
    self.rgb_model_backbone, self.rgb_model_branch = load_inference_model(self.rgb_model_backbone, self.rgb_model_branch, opt.rgb_model)
  File "../MOC_utils/model.py", line 82, in load_inference_model
    branch.load_state_dict(state_dict, strict=False)
  File "/home/ryan/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MOC_Det:
	size mismatch for branch.hm.2.weight: copying a param of torch.Size([24, 256, 1, 1]) from checkpoint, where the shape is torch.Size([5, 256, 1, 1]) in current model.
	size mismatch for branch.hm.2.bias: copying a param of torch.Size([24]) from checkpoint, where the shape is torch.Size([5]) in current model.
```
I tried both k7 and k1 model, and got the same error
Can you tell me how my model and yours are different?

**Comment by ArchiZX** [comment]
You have 5 classes, so set `--num_classes` as 5.

**Comment by npduyduc** [comment]
Thank you, I did it.
It seems like this way of consuming ram for long predictions, but it helped me a lot.
I'm trying to use k1 model to predict online streaming, the initial result looks good.
I'm doing:
```
read 2 frame from online streaming ---> frame1, frame2 ---> dense-optical-flow ---> flow-image ---> PrefetchDataset ---> ... 
(or video)                                                                          ---> frame1                   ---> rgb-image ---^
```
But now the predict code stops at the 2nd loop, I am trying to fix it
ps: dense optical flow is not good for ucf101 dataset but it is okay for my dataset when the camera is stable and does not shake

**Comment by ArchiZX** [comment]
I recommend using K=7 and rgb as input, for efficiency.

**Comment by npduyduc** [comment]
Hello, I take a lot of time to label my data. :'( 
I tried your recommendation and it was really good, I let live stream delay 7 frames to run the model with k = 7 and it showed promising results.
However, when I try to train my model with my dataset with k = 7 I get this error every time "train: [1] [6/123]"
I ran ok with k = 1, can you explan for me what did I miss ? Thank you!
```
Train_K7_flow_coco |#                               | train: [1][6/123]|Tot: 0:00:26 |ETA: 0:08:01 |loss 12.5521 |loss_hm 11.2235 |loss_mov 0.8385 |loss_wh 4.9010 Traceback (most recent call last):
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/train.py", line 167, in <module>
    main(opt)
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/train.py", line 95, in main
    log_dict_train = trainer.train(epoch, train_loader, train_writer)
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/trainer/moc_trainer.py", line 56, in train
    return self.run_epoch('train', epoch, data_loader, writer)
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/trainer/moc_trainer.py", line 74, in run_epoch
    for iter, batch in enumerate(data_loader):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 322, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/datasets/sample/sampler.py", line 26, in __getitem__
    images = [cv2.imread(self.imagefile(v, frame + i)).astype(np.float32) for i in range(K)]
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/datasets/sample/sampler.py", line 26, in <listcomp>
    images = [cv2.imread(self.imagefile(v, frame + i)).astype(np.float32) for i in range(K)]
AttributeError: 'NoneType' object has no attribute 'astype'

Exception ignored in: <function _DataLoaderIter.__del__ at 0x7f1fcb9a0170>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/usr/local/lib/python3.7/multiprocessing/queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/local/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/local/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 619, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by npduyduc** [comment]
Hello, I take a lot of time to label my data.
I tried your recommendation and it was really good, I let live stream delay 7 frames to run the model with k = 7 and it showed promising results.
However, when I try to train my model with my dataset with k = 7 I get this error every time "train: [1] [6/123]"
I ran okay with k = 1, can you explan for me what did I miss?
```
Train_K7_flow_coco |#                               | train: [1][6/123]|Tot: 0:01:31 |ETA: 0:27:36 |loss 12.5371 |loss_hm 11.2513 |loss_mov 0.8401 |loss_wh 4.4578 Traceback (most recent call last):
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/train.py", line 167, in <module>
    main(opt)
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/train.py", line 95, in main
    log_dict_train = trainer.train(epoch, train_loader, train_writer)
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/trainer/moc_trainer.py", line 56, in train
    return self.run_epoch('train', epoch, data_loader, writer)
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/trainer/moc_trainer.py", line 74, in run_epoch
    for iter, batch in enumerate(data_loader):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 322, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/datasets/sample/sampler.py", line 26, in __getitem__
    images = [cv2.imread(self.imagefile(v, frame + i)).astype(np.float32) for i in range(K)]
  File "/content/drive/My Drive/action_recognition/Moc-Detection/src/datasets/sample/sampler.py", line 26, in <listcomp>
    images = [cv2.imread(self.imagefile(v, frame + i)).astype(np.float32) for i in range(K)]
AttributeError: 'NoneType' object has no attribute 'astype'

Exception ignored in: <function _DataLoaderIter.__del__ at 0x7f0fb087b170>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/usr/local/lib/python3.7/multiprocessing/queues.py", line 354, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/local/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/local/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 619, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by ArchiZX** [comment]
'AttributeError: 'NoneType' object has no attribute 'astype''
It means that 'cv2.imread' gets an empty image file.

**Comment by npduyduc** [comment]
Hello, have a good day, I come with stupid questions again T_T
I want to ask you how should I judge the accuracy of the model?
I created test and run det.py to generate predictive results. I then calculated the difference of the bounding boxes using IoU and repeated them with true positive, false positive, false negative, and true negative.
How do you think it is?

**Comment by ArchiZX** [comment]
We provide codes for evaluating mAP in `ACT.py`.

If you have the same GT annotations and same detection results in each `.pkl` file, you can apply our evaluation methods in https://github.com/MCG-NJU/MOC-Detector/blob/master/readme/Evaluation.md (specifically in section `Evaluate mAP`).

**Comment by npduyduc** [comment]
Ohh you have written about it, sorry my level is not enough to fully understand, I am trying to read it, thank you.
Btw, I'm having trouble applying the model to detecting online. When 20 fps, the model recognizes very well, but when running online fps is only 1, and of course it will recognize a lot worse.
I am trying to increase inference speed when detecting online, by instead recognizing each frame, I do it for 7 frames at once, which means that instead of enqueue and dequeue 1 image at a time, I do 7 images at a time.
What do you think about it?

**Comment by ArchiZX** [comment]
Sorry, maybe I don't fully understand.

In subsection `Online Spatio-Temporal Action Detection` at https://github.com/MCG-NJU/MOC-Detector/blob/master/readme/Evaluation.md, I provide an online detection method using `stream_inference.py` which is suitable for real-time video stream. (As you say, enqueue and dequeue 1 image at a time)

If you directly use total K frames at a time, you will run codes in `normal_inference.py`. In this way the inference speed is very slow because of replicated computation for backbone feature.

btw, I don't understand the sentence `When 20 fps, the model recognizes very well, but when running online fps is only 1, and of course it will recognize a lot worse.`

**Comment by npduyduc** [comment]
My English is not good so I don't know, can I explain it to you?
I run it on my realtime camera, if an action happens in 3 seconds, with 20fps the number of input images will be 20x3 = 60, but 1fps the number of input images is just 3 for the same action taking place at the same time. Of course, when detected with 1 fps, the results were worse than 20 fps.

**Comment by ArchiZX** [comment]
Oh, I understand. You try a sparse sampling strategy for decreasing the frame rate.
This is really a good idea for increasing inference speed, but we do not consider it when design `Movement Branch`.
Since the movement across a long duration is hard to estimate by movement branch, our proposed method may not suit under this circumstance. But I think this is a novelty idea.

**Comment by ArchiZX** [comment]
@npduyduc Sorry, I wonder that whether you re-train a new model for fps=1, or just use the ready-made model train with fps=20?

**Comment by npduyduc** [comment]
It works well so I don't think about train another model. However, I guess model with fps = 1 will not be good. I'm doing the topic of street fights, and I don't think there's a punch for more than a second :))
So in my mind, I was just around the issue of increasing fps

**Comment by ArchiZX** [comment]
Oh that's it. The inference fps should be the same as training. Maybe you can train a new model with ground-truth annotation under fps=1.

**Comment by npduyduc** [comment]
I will try, but if so did I have missed your model's good thing? When there are fewer frames representing an action, does it affect the output of hm and the mov branch?

**Comment by ArchiZX** [comment]
Sorry I haven't done such experiments. In our task we focus more on density prediction with a high frame-rate. (depends on the dataset annotations) So I have no idea about the performance under the low frame-rate (in other word, sparse sampled frames). I also confuse about the movement branch generalization ability under this circumstance.

**Comment by npduyduc** [comment]
Thank you for your help. This problem happened because my server was too slow. v(ಥ ̯ ಥ)v

**Comment by npduyduc** [comment]
I want to ask you about the model evaluation, I tried creating your design output (pkl file) at ../result/default from the label file, but I still got this error:
```
inference_dirname is  ./output/fight/
threshold is  0.5
Traceback (most recent call last):
  File "ACT.py", line 383, in <module>
    frameAP(opt)
  File "ACT.py", line 108, in frameAP
    log_file = open(os.path.join(opt.root_dir, 'result', opt.exp_id), 'a+')
IsADirectoryError: [Errno 21] Is a directory: '/home/ryan/Desktop/PythonPJ/human-activity-recognition/MOC-Detector/src/../result/default'
```
Seems to have a log file at opt.exp_id, but I don't know what it is
Can you explan for me what did I miss?

**Comment by npduyduc** [comment]
I created following your output template in ../result/default from the label file. However, when running 
`python ACT.py --task frameAP --K 7 --th 0.5 - -inference_dir ./output/fight/ ` I got this error:
```
inference_dirname is  ./output/fight/
threshold is  0.5
Traceback (most recent call last):
  File "ACT.py", line 383, in <module>
    frameAP(opt)
  File "ACT.py", line 108, in frameAP
    log_file = open(os.path.join(opt.root_dir, 'result', opt.exp_id), 'a+')
IsADirectoryError: [Errno 21] Is a directory: '/home/ryan/Desktop/PythonPJ/human-activity-recognition/MOC-Detector/src/../result/default'
```
Seems to have a log file at opt.exp_id, but I don't know what it is
Can you explan for me what did I miss?

**Comment by npduyduc** [comment]
I want to ask you about model evaluation, I created following your output template (pkl file) at ../result/default from the label file, however, when running `python ACT.py --task frameAP` I got this error:
```
inference_dirname is  ./output/fight/
threshold is  0.5
Traceback (most recent call last):
  File "ACT.py", line 383, in <module>
    frameAP(opt)
  File "ACT.py", line 108, in frameAP
    log_file = open(os.path.join(opt.root_dir, 'result', opt.exp_id), 'a+')
IsADirectoryError: [Errno 21] Is a directory: '/home/ryan/Desktop/PythonPJ/human-activity-recognition/MOC-Detector/src/../result/default'
```
Seems to have a log file at opt.exp_id, but I don't know what it is
I can run `python ACT.py --task frameAP_error`, how are they different?
Can you explan for me what did I miss? Thank you!

**Comment by J3Chou** [comment]
> My English is not good so I don't know, can I explain it to you?
> I run it on my realtime camera, if an action happens in 3 seconds, with 20fps the number of input images will be 20x3 = 60, but 1fps the number of input images is just 3 for the same action taking place at the same time. When detected with 1 fps, the results were worse than 20 fps.

Hello, now I want to use the real-time camera to do online action recognition. It seems that this part is not implemented in the author's github library. Could you share the code you implemented to me?  Thank you!

**Comment by bit-scientist** [comment]
@npduyduc How do you prepare annotations for your custom dataset? Do you happen to have a step-by-step guideline to accomplish this?
